package com.github.itskenny0.r1ha.feature.panelgrid

import androidx.compose.ui.graphics.Color
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

val defaultHapanelsThemeConfig = HapanelsThemeConfig()

@Serializable
data class HapanelsThemeConfig(
    val preset: HapanelsThemePreset = HapanelsThemePreset.DEFAULT,
    val mode: HapanelsThemeMode = HapanelsThemeMode.DARK,
)

@Serializable
enum class HapanelsThemePreset {
    @SerialName("default") DEFAULT,
    @SerialName("light_breeze") LIGHT_BREEZE,
    @SerialName("desert_sun") DESERT_SUN,
    @SerialName("forest_leaves") FOREST_LEAVES,
    @SerialName("baltic_dawn") BALTIC_DAWN,
    @SerialName("bieszczady_sunset") BIESZCZADY_SUNSET,
    @SerialName("masurian_nights") MASURIAN_NIGHTS,
    @SerialName("aurora_glass") AURORA_GLASS,
    @SerialName("neon_noir") NEON_NOIR,
    @SerialName("velvet_spectrum") VELVET_SPECTRUM,
}

@Serializable
enum class HapanelsThemeMode {
    @SerialName("light") LIGHT,
    @SerialName("dark") DARK,
    @SerialName("system") SYSTEM,
}

data class HapanelsThemeColors(
    val panelBg: Color,
    val surface: Color,
    val surfaceVariant: Color,
    val primary: Color,
    val accent: Color,
    val textPrimary: Color,
    val textMuted: Color,
    val border: Color,
    val divider: Color,
    val hover: Color,
    val active: Color,
    val selected: Color,
    val danger: Color,
    val success: Color,
)

data class HapanelsThemeDefinition(
    val preset: HapanelsThemePreset,
    val name: String,
    val category: String,
    val description: String,
    val light: HapanelsThemeColors,
    val dark: HapanelsThemeColors,
)

fun HapanelsThemeConfig.resolveHapanelsThemeColors(
    isSystemInDarkTheme: Boolean = false,
): HapanelsThemeColors {
    val definition = resolveHapanelsThemeDefinition(preset)
    return when (mode) {
        HapanelsThemeMode.LIGHT -> definition.light
        HapanelsThemeMode.DARK -> definition.dark
        HapanelsThemeMode.SYSTEM -> if (isSystemInDarkTheme) definition.dark else definition.light
    }
}

fun resolveHapanelsThemeDefinition(
    preset: HapanelsThemePreset,
): HapanelsThemeDefinition = hapanelsThemeDefinitions.first { it.preset == preset }

val hapanelsThemeDefinitions = listOf(
    HapanelsThemeDefinition(
        preset = HapanelsThemePreset.DEFAULT,
        name = "Domyślny",
        category = "Wygląd domyślny",
        description = "Aktualny ciemny wygląd panelu Hapanels.",
        light = colors(
            panelBg = 0xFFF8FAFC,
            surface = 0xFFFFFFFF,
            surfaceVariant = 0xFFE7EAF0,
            primary = 0xFFE99900,
            accent = 0xFFE99900,
            textPrimary = 0xFF171A20,
            textMuted = 0xFF666A73,
            border = 0xFFD4D8E0,
            divider = 0xFFE3E6EC,
            hover = 0xFFFFF3D6,
            active = 0xFFFFE4A3,
            selected = 0xFFFFD980,
            danger = 0xFFFF5338,
            success = 0xFF2F9E44,
        ),
        dark = colors(
            panelBg = 0xFF090D10,
            surface = 0xFF23242D,
            surfaceVariant = 0xFF2E303A,
            primary = 0xFFE99900,
            accent = 0xFFE99900,
            textPrimary = 0xFFFFFFFF,
            textMuted = 0xFF888C96,
            border = 0xFF3A3D48,
            divider = 0xFF2C2E38,
            hover = 0xFF30313A,
            active = 0xFF3A3321,
            selected = 0xFF4B3A16,
            danger = 0xFFFF5338,
            success = 0xFF58C56A,
        ),
    ),
    HapanelsThemeDefinition(
        preset = HapanelsThemePreset.LIGHT_BREEZE,
        name = "Light Breeze",
        category = "Wygląd monochromatyczny",
        description = "Chłodny, jasny błękit z lekkim kontrastem.",
        light = colors(
            panelBg = 0xFFF4FAFF,
            surface = 0xFFFFFFFF,
            surfaceVariant = 0xFFDDECF7,
            primary = 0xFF0B6FA4,
            accent = 0xFF3FA7D6,
            textPrimary = 0xFF10202C,
            textMuted = 0xFF5D7482,
            border = 0xFFC2D7E6,
            divider = 0xFFD8E7F0,
            hover = 0xFFEAF6FD,
            active = 0xFFD3EDFA,
            selected = 0xFFB8E1F4,
            danger = 0xFFBA1A1A,
            success = 0xFF1B7F4C,
        ),
        dark = colors(
            panelBg = 0xFF07141C,
            surface = 0xFF132832,
            surfaceVariant = 0xFF203946,
            primary = 0xFF8BD3F7,
            accent = 0xFF51B7E8,
            textPrimary = 0xFFEAF8FF,
            textMuted = 0xFF9DB8C8,
            border = 0xFF315260,
            divider = 0xFF25434F,
            hover = 0xFF1B3440,
            active = 0xFF254C5D,
            selected = 0xFF2F6177,
            danger = 0xFFFFB4AB,
            success = 0xFF7DDFA2,
        ),
    ),
    HapanelsThemeDefinition(
        preset = HapanelsThemePreset.DESERT_SUN,
        name = "Desert Sun",
        category = "Wygląd monochromatyczny",
        description = "Ciepły piasek i bursztyn.",
        light = colors(
            panelBg = 0xFFFFF8EE,
            surface = 0xFFFFFCF7,
            surfaceVariant = 0xFFF1E0C8,
            primary = 0xFF8A5A00,
            accent = 0xFFD99A21,
            textPrimary = 0xFF2A1B06,
            textMuted = 0xFF765F3F,
            border = 0xFFD8C29D,
            divider = 0xFFE8D8BF,
            hover = 0xFFFFEFD2,
            active = 0xFFFFE1A6,
            selected = 0xFFFFD27A,
            danger = 0xFFBA1A1A,
            success = 0xFF4D7D22,
        ),
        dark = colors(
            panelBg = 0xFF1B1205,
            surface = 0xFF2D2110,
            surfaceVariant = 0xFF41321A,
            primary = 0xFFFFC66B,
            accent = 0xFFEAA12A,
            textPrimary = 0xFFFFF3DF,
            textMuted = 0xFFD1B98F,
            border = 0xFF5D4725,
            divider = 0xFF4A391E,
            hover = 0xFF3A2B16,
            active = 0xFF5A421D,
            selected = 0xFF705222,
            danger = 0xFFFFB4AB,
            success = 0xFFA8D96F,
        ),
    ),
    HapanelsThemeDefinition(
        preset = HapanelsThemePreset.FOREST_LEAVES,
        name = "Forest Leaves",
        category = "Wygląd monochromatyczny",
        description = "Zielenie lasu, spokojne i kontrastowe.",
        light = colors(
            panelBg = 0xFFF4FBF2,
            surface = 0xFFFFFFFF,
            surfaceVariant = 0xFFDCEBD7,
            primary = 0xFF2F6B2F,
            accent = 0xFF5C9E46,
            textPrimary = 0xFF11210F,
            textMuted = 0xFF5F7358,
            border = 0xFFC3D6BD,
            divider = 0xFFD7E4D2,
            hover = 0xFFEAF6E6,
            active = 0xFFD9EFD2,
            selected = 0xFFC3E6B9,
            danger = 0xFFBA1A1A,
            success = 0xFF1B7F4C,
        ),
        dark = colors(
            panelBg = 0xFF081409,
            surface = 0xFF172619,
            surfaceVariant = 0xFF263828,
            primary = 0xFFA8D99B,
            accent = 0xFF7DBB63,
            textPrimary = 0xFFEFF8EC,
            textMuted = 0xFFA8BFA0,
            border = 0xFF3A5138,
            divider = 0xFF2D422D,
            hover = 0xFF203321,
            active = 0xFF31502F,
            selected = 0xFF3E6339,
            danger = 0xFFFFB4AB,
            success = 0xFF8FE0A7,
        ),
    ),
    HapanelsThemeDefinition(
        preset = HapanelsThemePreset.BALTIC_DAWN,
        name = "Bałtyk o świcie",
        category = "Polskie inspiracje",
        description = "Morski błękit, mgła i różowy świt.",
        light = colors(
            panelBg = 0xFFF3FAFA,
            surface = 0xFFFFFFFF,
            surfaceVariant = 0xFFD7E9EA,
            primary = 0xFF1B6F7A,
            accent = 0xFFE8918E,
            textPrimary = 0xFF0F2326,
            textMuted = 0xFF60777A,
            border = 0xFFBFD6D8,
            divider = 0xFFD4E4E5,
            hover = 0xFFE6F4F5,
            active = 0xFFCDECEF,
            selected = 0xFFFFDAD8,
            danger = 0xFFBA1A1A,
            success = 0xFF1B7F4C,
        ),
        dark = colors(
            panelBg = 0xFF061416,
            surface = 0xFF14282B,
            surfaceVariant = 0xFF233A3E,
            primary = 0xFF8AD7DF,
            accent = 0xFFFFB4B0,
            textPrimary = 0xFFEAF8F9,
            textMuted = 0xFFA5BCBF,
            border = 0xFF365459,
            divider = 0xFF29454A,
            hover = 0xFF1D3438,
            active = 0xFF2B5157,
            selected = 0xFF613735,
            danger = 0xFFFFB4AB,
            success = 0xFF81DFA7,
        ),
    ),
    HapanelsThemeDefinition(
        preset = HapanelsThemePreset.BIESZCZADY_SUNSET,
        name = "Bieszczadzkie zachody",
        category = "Polskie inspiracje",
        description = "Ciepły zachód nad połoninami.",
        light = colors(
            panelBg = 0xFFFFF7F0,
            surface = 0xFFFFFCF9,
            surfaceVariant = 0xFFF1DED2,
            primary = 0xFF8C4A2F,
            accent = 0xFFD06A3A,
            textPrimary = 0xFF2B170F,
            textMuted = 0xFF765F55,
            border = 0xFFD9C1B5,
            divider = 0xFFE8D7CE,
            hover = 0xFFFFEDE3,
            active = 0xFFFFD9C8,
            selected = 0xFFFFC4A8,
            danger = 0xFFBA1A1A,
            success = 0xFF3F7E3D,
        ),
        dark = colors(
            panelBg = 0xFF1A0E0A,
            surface = 0xFF2C1D17,
            surfaceVariant = 0xFF432E25,
            primary = 0xFFFFB69A,
            accent = 0xFFFF8D57,
            textPrimary = 0xFFFFF1EA,
            textMuted = 0xFFD4B5A6,
            border = 0xFF60463A,
            divider = 0xFF4D382F,
            hover = 0xFF392820,
            active = 0xFF5B3E31,
            selected = 0xFF734E3C,
            danger = 0xFFFFB4AB,
            success = 0xFF9DD990,
        ),
    ),
    HapanelsThemeDefinition(
        preset = HapanelsThemePreset.MASURIAN_NIGHTS,
        name = "Mazurskie noce",
        category = "Polskie inspiracje",
        description = "Granat jezior i nocne światło.",
        light = colors(
            panelBg = 0xFFF5F8FF,
            surface = 0xFFFFFFFF,
            surfaceVariant = 0xFFDDE6F6,
            primary = 0xFF2C5C9A,
            accent = 0xFF7F96D6,
            textPrimary = 0xFF121D2F,
            textMuted = 0xFF626F86,
            border = 0xFFC5D2E8,
            divider = 0xFFD9E2F2,
            hover = 0xFFECF3FF,
            active = 0xFFDCEBFF,
            selected = 0xFFC7DBFF,
            danger = 0xFFBA1A1A,
            success = 0xFF1F7A5A,
        ),
        dark = colors(
            panelBg = 0xFF070D1A,
            surface = 0xFF171E31,
            surfaceVariant = 0xFF252E46,
            primary = 0xFFAFC7FF,
            accent = 0xFF8EA7F2,
            textPrimary = 0xFFEFF3FF,
            textMuted = 0xFFAEB8D0,
            border = 0xFF3B4663,
            divider = 0xFF2F3852,
            hover = 0xFF202840,
            active = 0xFF334061,
            selected = 0xFF405079,
            danger = 0xFFFFB4AB,
            success = 0xFF75DDB8,
        ),
    ),
    HapanelsThemeDefinition(
        preset = HapanelsThemePreset.AURORA_GLASS,
        name = "Aurora Glass",
        category = "Kolorowe abstrakcyjne",
        description = "Szklany gradient zorzy z chłodnym fioletem i cyjanem.",
        light = colors(
            panelBg = 0xFFF7F8FF,
            surface = 0xFFFFFFFF,
            surfaceVariant = 0xFFE7E4FF,
            primary = 0xFF5F4AE0,
            accent = 0xFF20BFD6,
            textPrimary = 0xFF151427,
            textMuted = 0xFF686785,
            border = 0xFFD4D0F5,
            divider = 0xFFE2DFF7,
            hover = 0xFFF0EEFF,
            active = 0xFFE2DDFF,
            selected = 0xFFD7F6FB,
            danger = 0xFFBA1A1A,
            success = 0xFF137D5A,
        ),
        dark = colors(
            panelBg = 0xFF080817,
            surface = 0xFF17162B,
            surfaceVariant = 0xFF252344,
            primary = 0xFFC7BEFF,
            accent = 0xFF69E4F4,
            textPrimary = 0xFFF4F1FF,
            textMuted = 0xFFB7B1D9,
            border = 0xFF3D3A66,
            divider = 0xFF302E55,
            hover = 0xFF201F3A,
            active = 0xFF332F62,
            selected = 0xFF214B5A,
            danger = 0xFFFFB4AB,
            success = 0xFF7BE0BE,
        ),
    ),
    HapanelsThemeDefinition(
        preset = HapanelsThemePreset.NEON_NOIR,
        name = "Neon Noir",
        category = "Kolorowe abstrakcyjne",
        description = "Ciemny premium look z neonowym magenta i elektrycznym błękitem.",
        light = colors(
            panelBg = 0xFFFFF7FB,
            surface = 0xFFFFFFFF,
            surfaceVariant = 0xFFFFDDEC,
            primary = 0xFF9B1B6A,
            accent = 0xFF0078D4,
            textPrimary = 0xFF26111E,
            textMuted = 0xFF795D70,
            border = 0xFFE8BED5,
            divider = 0xFFF2D5E4,
            hover = 0xFFFFEDF6,
            active = 0xFFFFD9EB,
            selected = 0xFFD7ECFF,
            danger = 0xFFBA1A1A,
            success = 0xFF167A56,
        ),
        dark = colors(
            panelBg = 0xFF09040D,
            surface = 0xFF1B1022,
            surfaceVariant = 0xFF31183C,
            primary = 0xFFFFA8D8,
            accent = 0xFF58C7FF,
            textPrimary = 0xFFFFEEF8,
            textMuted = 0xFFD1A7C4,
            border = 0xFF53305F,
            divider = 0xFF41254D,
            hover = 0xFF271430,
            active = 0xFF421C54,
            selected = 0xFF193F5C,
            danger = 0xFFFFB4AB,
            success = 0xFF72DDB4,
        ),
    ),
    HapanelsThemeDefinition(
        preset = HapanelsThemePreset.VELVET_SPECTRUM,
        name = "Velvet Spectrum",
        category = "Kolorowe abstrakcyjne",
        description = "Miękki, luksusowy miks śliwki, złota i indygo.",
        light = colors(
            panelBg = 0xFFFFF8F4,
            surface = 0xFFFFFFFF,
            surfaceVariant = 0xFFF0DDEA,
            primary = 0xFF74406F,
            accent = 0xFFC18A2A,
            textPrimary = 0xFF251524,
            textMuted = 0xFF735C6D,
            border = 0xFFDDC2D5,
            divider = 0xFFEBD7E5,
            hover = 0xFFFFEFF8,
            active = 0xFFF2D4E8,
            selected = 0xFFFFE0A8,
            danger = 0xFFBA1A1A,
            success = 0xFF397A45,
        ),
        dark = colors(
            panelBg = 0xFF100913,
            surface = 0xFF211426,
            surfaceVariant = 0xFF35203C,
            primary = 0xFFE8B7E5,
            accent = 0xFFE4B65C,
            textPrimary = 0xFFFFF0FA,
            textMuted = 0xFFC7A8C4,
            border = 0xFF56355F,
            divider = 0xFF442B4C,
            hover = 0xFF2D1934,
            active = 0xFF4B2758,
            selected = 0xFF60481F,
            danger = 0xFFFFB4AB,
            success = 0xFF9BD894,
        ),
    ),
)

private fun colors(
    panelBg: Long,
    surface: Long,
    surfaceVariant: Long,
    primary: Long,
    accent: Long,
    textPrimary: Long,
    textMuted: Long,
    border: Long,
    divider: Long,
    hover: Long,
    active: Long,
    selected: Long,
    danger: Long,
    success: Long,
) = HapanelsThemeColors(
    panelBg = Color(panelBg),
    surface = Color(surface),
    surfaceVariant = Color(surfaceVariant),
    primary = Color(primary),
    accent = Color(accent),
    textPrimary = Color(textPrimary),
    textMuted = Color(textMuted),
    border = Color(border),
    divider = Color(divider),
    hover = Color(hover),
    active = Color(active),
    selected = Color(selected),
    danger = Color(danger),
    success = Color(success),
)
